name: Build Direct3D_Win32_DR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Build the solution using MSBuild from Visual Studio
      - name: Build solution
        run: |
          "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe" Direct3D_Win32_DR.sln /p:Configuration=Release /p:Platform=x64
